name: 'g4g-java-dockerizer tool executor'
description: 'g4g-java-dockerizer CLI executor'
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: mendinuetaj/g4g-java-dockerizer-tool-installer@1.4
    - run: $GITHUB_WORKSPACE/g4g-java-builder